name: Run linter and formatter

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '20'

    - name: Install pnpm
      run: curl -f https://get.pnpm.io/v6.js | node - add --global pnpm

    - name: Install Turborepo
      run: pnpm install turbo --global

    - name: Install dependencies
      run: pnpm install

    - name: Run tests
      run: |
        pnpm lint
        pnpm format